ant_network:
  frequency: 57
  key:
  - 185
  - 165
  - 33
  - 251
  - 189
  - 114
  - 195
  - 69
app:
  backend: openant
  data_display_interval: 1
  found_devices_file: data/found_devices.json
  scan_timeout: 30
devices:
  bike_data:
    device_id: null
    device_type: 121
    enabled: true
  heart_rate:
    device_id: 25377
    device_type: 120
    enabled: true
mqtt:
  base_topic: pyantdisplay
  client_id: pyantdisplay-mqtt
  discovery: true
  discovery_prefix: homeassistant
  host: localhost
  password: null
  port: 1883
  qos: 1
  retain: true
  stale_secs: 10
  tls: false
  username: null
